/* Autogenerated file. Do not edit manually. */

/* tslint:disable */
/* eslint-disable */

/*
  Fuels version: 0.82.0
  Forc version: 0.49.3
  Fuel-Core version: 0.22.1
*/

export type { AMMContractAbi } from './AMMContractAbi';

export { AMMContractAbi__factory } from './factories/AMMContractAbi__factory';
